# MAJOR=2
# MINOR=1
# PATCH=0
# BUILD=135
# SYSTEM_CONFIG_VERSION:=$(MAJOR).$(MINOR).$(PATCH).$(BUILD)
# export SYSTEM_CONFIG_VERSION
# export SYSTEM_CONFIG_MAJOR=$(MAJOR)
# export SYSTEM_CONFIG_MINOR=$(MINOR)
# export SYSTEM_CONFIG_PATCH=$(PATCH)
# export SYSTEM_CONFIG_BUILD=$(BUILD)
IMG_RELEASE=2.1.0
